name: lint

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  cpp:
    name: cpp
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: jidicula/clang-format-action@654a770daa28443dd111d133e4083e21c1075674  # v4.18.0
        name: clang-format
        with:
          clang-format-version: "15"
          check-path: "src"

  js:
    name: js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1

      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        name: Install pnpm and Node.js
        with:
          runtime: node@20
          cache: true
          install: false

      - run: pnpm install --frozen-lockfile
        name: Install dependencies

      - run: pnpm exec eslint .
        name: ESLint
