name: tests

on:
  push:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: make setup
        name: Setup

      - run: echo "version=$(make emscripten-version)" >> $GITHUB_OUTPUT
        id: emscripten-version
        name: Get emscripten version

      - uses: actions/cache/restore@v3
        name: Restore emscripten cache
        id: emscripten-cache
        with:
          path: ${{ github.workspace }}/emscripten_cache
          key: ${{ runner.os }}-emscripten-${{ steps.emscripten-version.outputs.version }}

      - run: make build
        name: Build
        env:
          EM_CACHE: ${{ github.workspace }}/emscripten_cache

      - run: make install
        name: Install

      - run: npm test
        name: Test

      - uses: actions/upload-artifact@v3
        name: Upload artifacts
        with:
          name: opentimelineio
          path: install/
        if: success() || failure()

      - uses: actions/cache/save@v3
        name: Save emscripten cache
        with:
          path: ${{ github.workspace }}/emscripten_cache
          key: ${{ steps.emscripten-cache.outputs.cache-primary-key }}
        if: (success() || failure()) && steps.emscripten-cache.outputs.cache-hit != 'true'
