name: tests

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    name: Test (${{ matrix.build-type }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-type: [Release, Debug]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          submodules: true

      - uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        name: Install pnpm and Node.js
        with:
          runtime: node@20
          cache: true
          install: false

      - run: make setup
        name: Setup

      - run: echo "version=$(make emscripten-version)" >> $GITHUB_OUTPUT
        id: emscripten-version
        name: Get emscripten version

      - uses: actions/cache/restore@v3
        name: Restore emscripten cache
        id: emscripten-cache
        with:
          path: ${{ github.workspace }}/emscripten_cache
          key: ${{ runner.os }}-emscripten-${{ steps.emscripten-version.outputs.version }}-${{ matrix.build-type }}

      - run: make build BUILD_TYPE=${{ matrix.build-type }}
        name: Build
        env:
          EM_CACHE: ${{ github.workspace }}/emscripten_cache

      - run: make install
        name: Install

      - run: pnpm test
        name: Test

      - uses: actions/upload-artifact@v4
        name: Upload artifacts
        with:
          name: opentimelineio-${{ matrix.build-type }}
          path: install/
        if: success() || failure()

      - uses: actions/cache/save@v3
        name: Save emscripten cache
        with:
          path: ${{ github.workspace }}/emscripten_cache
          key: ${{ steps.emscripten-cache.outputs.cache-primary-key }}
        if: (success() || failure()) && steps.emscripten-cache.outputs.cache-hit != 'true'
