name: tests

on:
  push:

env:
  EM_CACHE: emscripten_cache

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-node@v3
        with:
          node-version: 19

      - run: make setup
        name: Setup

      - run: echo "version=$(make emscripten-version)" >> $GITHUB_OUTPUT
        id: emscripten-version
        name: Get emscripten version

      - uses: actions/cache@v3
        name: Emscripten cache
        with:
          path: ${{ env.EM_CACHE }}
          key: ${{ runner.os }}-emscripten-${{ steps.emscripten-version.outputs.version }}

      - run: make build
        name: Build

      - run: make install
        name: Install

      - run: npm test
        name: Test
